### ISSUE TITLE
你好，请问你是怎么拿到请求体里面的数据的

### ISSUE THREAD

**Issue by yaodi962464** [winterfell2021/lostark_wegame_helper#1]

**Comment by winterfell2021** [comment]
See https://github.com/winterfell2021/lostark_wegame_helper/blob/master/tech.md

**Comment by intAV** [comment]
哥 你简直太牛了 我是搜索api2.helper.qq.com来到这里的
没想到真的有牛人
关于这个app我唯一想得到的就是那个流浪商人，但是我通过代理抓包是加密的乱码，请问这种情况下能解密拿到请求参数和返回结果吗
![image](https://github.com/user-attachments/assets/ace34ccc-32a8-4196-8feb-84dd2a086d19)
上面就是获取流浪商人的包
很期待你的回复！！！
